### ISSUE TITLE
AttributeError: 'Image' object has no attribute '_VImageAdapter__inputref'

### ISSUE THREAD

**Issue by dazza-codes** [ecometrica/gdal2mbtiles#32]
```
Traceback (most recent call last):
  File "/opt/conda/envs/gis-dataprocessing/bin/gdal2mbtiles", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/gdal2mbtiles/main.py", line 309, in main
    colors=colors, band=band)
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/gdal2mbtiles/helpers.py", line 211, in warp_mbtiles
    pngdata=pngdata)
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/gdal2mbtiles/helpers.py", line 73, in image_mbtiles
    pyramid = preprocessor(**locals())
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/gdal2mbtiles/helpers.py", line 324, in resample_after_warp
    pyramid.dataset.resample(resolution=resolution)
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/gdal2mbtiles/vips.py", line 601, in resample
    ratios=self.GetScalingRatios(resolution=resolution, places=5)
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/gdal2mbtiles/vips.py", line 582, in _resample
    output_size=(dst_width, dst_height)
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/gdal2mbtiles/vips.py", line 392, in stretch
    interpolate='near'
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/gdal2mbtiles/vips.py", line 349, in _scale
    interpolate=interpolate)
  File "/opt/conda/envs/gis-dataprocessing/lib/python3.7/site-packages/gdal2mbtiles/vips.py", line 281, in affine
    image.__inputref = self.image
AttributeError: 'Image' object has no attribute '_VImageAdapter__inputref'
```

Versions
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
$ vips --version
vips-8.4.5-Wed Jan 18 12:36:44 UTC 2017
$ gdalinfo --version
GDAL 2.4.2, released 2019/06/28
$ pip freeze | grep gdal
gdal2mbtiles==2.1.1
$ pip freeze | grep proj
pyproj==2.2.1
$ pip freeze | grep rasterio
rasterio==1.0.28
```

**Comment by jordiecometrica** [comment]
What was your invocation? Can you provide a sample image?

**Comment by dazza-codes** [comment]
Command:
```
gdal2mbtiles --name {name} --layer-type overlay --format png --spatial-reference 3857 --resampling bilinear --min-resolution 2 --max-resolution 18 --no-fill-borders --png8 256 input.tif output.mbtiles
```
Sorry, I can't provide the exact GeoTIFF input (it's private company data).  All I can say about it is that it is output from WRF models and it matches EPSG:26904.

**Comment by dazza-codes** [comment]
I've forked the source to look into this and created a virtualenv with conda to run it locally and it segfaults 🤕 

Where are the instructions on how to create a development environment for this project?  A `CONTRIBUTING.md` file or something like that would really help.  If you want to welcome contributions, please start by making it easier to do so.  For example, there's no information on how to create development environment and run the unit tests for this project.  The project is lacking a robust definition of it's dependencies - it's not really sufficient to only use this project with a bunch of ubuntu packages - maybe this is better off as a conda package or something.  If the project is built and tested in a docker image, please provide information on how that works.  All of these points would really help working on it to make some kind of contribution or at least debug our errors.

**Comment by zaakzaku** [comment]
Same error 
gdal2mbtiles omd.tif ./test/test.mbtiles --png8 4
Traceback (most recent call last):
  File "/usr/local/bin/gdal2mbtiles", line 11, in <module>
    load_entry_point('gdal2mbtiles==2.1.1', 'console_scripts', 'gdal2mbtiles')()
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles/main.py", line 309, in main
    colors=colors, band=band)
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles/helpers.py", line 211, in warp_mbtiles
    pngdata=pngdata)
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles/helpers.py", line 73, in image_mbtiles
    pyramid = preprocessor(**locals())
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles/helpers.py", line 324, in resample_after_warp
    pyramid.dataset.resample(resolution=resolution)
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles/vips.py", line 601, in resample
    ratios=self.GetScalingRatios(resolution=resolution, places=5)
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles/vips.py", line 582, in _resample
    output_size=(dst_width, dst_height)
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles/vips.py", line 392, in stretch
    interpolate='near'
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles/vips.py", line 349, in _scale
    interpolate=interpolate)
  File "/usr/local/lib/python3.6/dist-packages/gdal2mbtiles/vips.py", line 281, in affine
    image.__inputref = self.image
AttributeError: 'Image' object has no attribute '_VImageAdapter__inputref'

**Comment by dazza-codes** [comment]
There's some non-pure function stuff going on in
- https://github.com/ecometrica/gdal2mbtiles/blob/master/gdal2mbtiles/vips.py#L250
- esp. problematic because it manipulates a dunder attr - really bad practice

i.e. yea, woa, nasty stuff that probably shouldn't pass a code review

```
        # Link output to self, because its buffer is related to self.image()
        # We don't want self to get destructed in C++ when Python garbage
        # collects self if it falls out of scope.

        image = self.image.affine(
            [a, b, c, d],
            interpolate=interpolate,
            oarea=[ox, oy, ow, oh],
            odx=dx, ody=dy,
            idx=0, idy=0
        )
        image.__inputref = self.image
        # output = VIPS.im_affinei(self.image, self.image.copy(), interpolate,
        #                 a, b, c, d, dx, dy, ox, oy, ow, oh)
```

**Comment by dazza-codes** [comment]
I'm not sure if it's intended to fix this issue, but https://github.com/ecometrica/gdal2mbtiles/commit/0e10e229ddb3e90bb57dddf2d5e9cd52b9de0003 is the same version of pyvips that was working a couple months ago in a docker image that was built then (a conda env export from the docker container of that image output `pyvips==2.1.8`).

**Comment by damon-rand** [comment]
@dazza-codes Thanks for looking into it at length. We have been looking in to it as well internally but have limited resources. A lot of this library was written by individuals who have since moved on so please bear with us. IIRC the switch to pyvips 2 years ago was for Python 3 compatibly going forward.

**Comment by dazza-codes** [comment]
@damon-rand - if ecometrica has little use for this and/or plans to drop support for it (or at least has very limited support/update cycles), another option might be https://github.com/mapbox/rio-mbtiles.  Although the README indicates that it has some file size limitations and I haven't compared performance, maybe contributions and maintenance/updates will be more reliable from the mapbox team.

**Comment by damon-rand** [comment]
@dazza-codes We did push a fix/release to pin pyvips. Please let us know if that solves your issue.

**Comment by dazza-codes** [comment]
@damon-rand - pinning pyvips did the trick when it was added to my project dependencies and pinned.  Now that the pin is part of this project, the extra requirement on my project could be removed.  Although I haven't yet tested that, I would expect that fixes this issue (close at will).
